// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.ct_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_ct_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_ct_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles.
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "ct_core"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "ct_core"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_ct_core_checksum_func_codex_remote_decode_health_json(
    ): Short
    external fun uniffi_ct_core_checksum_func_codex_remote_decode_thread_detail_json(
    ): Short
    external fun uniffi_ct_core_checksum_func_codex_remote_decode_thread_list_json(
    ): Short
    external fun uniffi_ct_core_checksum_func_codex_remote_decode_turn_submit_json(
    ): Short
    external fun uniffi_ct_core_checksum_func_codex_remote_turn_stream_apply_event_json(
    ): Short
    external fun uniffi_ct_core_checksum_func_codex_remote_turn_stream_empty_projection(
    ): Short
    external fun uniffi_ct_core_checksum_func_codex_remote_wire_contract_version(
    ): Short
    external fun uniffi_ct_core_checksum_func_portable_config_decode_json(
    ): Short
    external fun uniffi_ct_core_checksum_func_portable_config_empty_document(
    ): Short
    external fun uniffi_ct_core_checksum_func_portable_config_encode_json(
    ): Short
    external fun uniffi_ct_core_checksum_func_portable_config_validate(
    ): Short
    external fun ffi_ct_core_uniffi_contract_version(
    ): Int


}

internal object UniffiLib {


    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "ct_core"))

    }
    external fun uniffi_ct_core_fn_func_codex_remote_decode_health_json(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_codex_remote_decode_thread_detail_json(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_codex_remote_decode_thread_list_json(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_codex_remote_decode_turn_submit_json(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_codex_remote_turn_stream_apply_event_json(`projection`: RustBuffer.ByValue,`eventJson`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_codex_remote_turn_stream_empty_projection(uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_codex_remote_wire_contract_version(uniffi_out_err: UniffiRustCallStatus,
    ): Int
    external fun uniffi_ct_core_fn_func_portable_config_decode_json(`input`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_portable_config_empty_document(uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_portable_config_encode_json(`document`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun uniffi_ct_core_fn_func_portable_config_validate(`document`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun ffi_ct_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun ffi_ct_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun ffi_ct_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus,
    ): Unit
    external fun ffi_ct_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun ffi_ct_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Byte
    external fun ffi_ct_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Byte
    external fun ffi_ct_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Short
    external fun ffi_ct_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Short
    external fun ffi_ct_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Int
    external fun ffi_ct_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Int
    external fun ffi_ct_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Long
    external fun ffi_ct_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Long
    external fun ffi_ct_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Float
    external fun ffi_ct_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Double
    external fun ffi_ct_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): RustBuffer.ByValue
    external fun ffi_ct_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_ct_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus,
    ): Unit


}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_ct_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_ct_core_checksum_func_codex_remote_decode_health_json() != 5393.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_codex_remote_decode_thread_detail_json() != 27944.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_codex_remote_decode_thread_list_json() != 64558.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_codex_remote_decode_turn_submit_json() != 1955.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_codex_remote_turn_stream_apply_event_json() != 17698.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_codex_remote_turn_stream_empty_projection() != 42965.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_codex_remote_wire_contract_version() != 54092.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_portable_config_decode_json() != 15857.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_portable_config_empty_document() != 45139.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_portable_config_encode_json() != 51109.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_ct_core_checksum_func_portable_config_validate() != 34450.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/**
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/**
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class FfiCodexRemoteControlEndpoint (
    var `baseUrl`: kotlin.String
    ,
    var `credentialRef`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteControlEndpoint: FfiConverterRustBuffer<FfiCodexRemoteControlEndpoint> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteControlEndpoint {
        return FfiCodexRemoteControlEndpoint(
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteControlEndpoint) = (
            FfiConverterString.allocationSize(value.`baseUrl`) +
            FfiConverterOptionalString.allocationSize(value.`credentialRef`)
    )

    override fun write(value: FfiCodexRemoteControlEndpoint, buf: ByteBuffer) {
            FfiConverterString.write(value.`baseUrl`, buf)
            FfiConverterOptionalString.write(value.`credentialRef`, buf)
    }
}



data class FfiCodexRemoteHealth (
    var `service`: kotlin.String
    ,
    var `version`: kotlin.String
    ,
    var `os`: kotlin.String
    ,
    var `arch`: kotlin.String
    ,
    var `appServerAvailable`: kotlin.Boolean
    ,
    var `appServerProbe`: kotlin.String
    ,
    var `codexHome`: kotlin.String

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteHealth: FfiConverterRustBuffer<FfiCodexRemoteHealth> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteHealth {
        return FfiCodexRemoteHealth(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteHealth) = (
            FfiConverterString.allocationSize(value.`service`) +
            FfiConverterString.allocationSize(value.`version`) +
            FfiConverterString.allocationSize(value.`os`) +
            FfiConverterString.allocationSize(value.`arch`) +
            FfiConverterBoolean.allocationSize(value.`appServerAvailable`) +
            FfiConverterString.allocationSize(value.`appServerProbe`) +
            FfiConverterString.allocationSize(value.`codexHome`)
    )

    override fun write(value: FfiCodexRemoteHealth, buf: ByteBuffer) {
            FfiConverterString.write(value.`service`, buf)
            FfiConverterString.write(value.`version`, buf)
            FfiConverterString.write(value.`os`, buf)
            FfiConverterString.write(value.`arch`, buf)
            FfiConverterBoolean.write(value.`appServerAvailable`, buf)
            FfiConverterString.write(value.`appServerProbe`, buf)
            FfiConverterString.write(value.`codexHome`, buf)
    }
}



data class FfiCodexRemoteHealthDecodeResult (
    var `health`: FfiCodexRemoteHealth?
    ,
    var `errorMessage`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteHealthDecodeResult: FfiConverterRustBuffer<FfiCodexRemoteHealthDecodeResult> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteHealthDecodeResult {
        return FfiCodexRemoteHealthDecodeResult(
            FfiConverterOptionalTypeFfiCodexRemoteHealth.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteHealthDecodeResult) = (
            FfiConverterOptionalTypeFfiCodexRemoteHealth.allocationSize(value.`health`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FfiCodexRemoteHealthDecodeResult, buf: ByteBuffer) {
            FfiConverterOptionalTypeFfiCodexRemoteHealth.write(value.`health`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}



data class FfiCodexRemoteThreadDetail (
    var `id`: kotlin.String
    ,
    var `title`: kotlin.String
    ,
    var `status`: kotlin.String
    ,
    var `updatedAt`: kotlin.String
    ,
    var `cwd`: kotlin.String?
    ,
    var `transcript`: List<FfiCodexRemoteTranscriptRow>

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteThreadDetail: FfiConverterRustBuffer<FfiCodexRemoteThreadDetail> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteThreadDetail {
        return FfiCodexRemoteThreadDetail(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterSequenceTypeFfiCodexRemoteTranscriptRow.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteThreadDetail) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`status`) +
            FfiConverterString.allocationSize(value.`updatedAt`) +
            FfiConverterOptionalString.allocationSize(value.`cwd`) +
            FfiConverterSequenceTypeFfiCodexRemoteTranscriptRow.allocationSize(value.`transcript`)
    )

    override fun write(value: FfiCodexRemoteThreadDetail, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`status`, buf)
            FfiConverterString.write(value.`updatedAt`, buf)
            FfiConverterOptionalString.write(value.`cwd`, buf)
            FfiConverterSequenceTypeFfiCodexRemoteTranscriptRow.write(value.`transcript`, buf)
    }
}



data class FfiCodexRemoteThreadDetailDecodeResult (
    var `thread`: FfiCodexRemoteThreadDetail?
    ,
    var `errorMessage`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteThreadDetailDecodeResult: FfiConverterRustBuffer<FfiCodexRemoteThreadDetailDecodeResult> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteThreadDetailDecodeResult {
        return FfiCodexRemoteThreadDetailDecodeResult(
            FfiConverterOptionalTypeFfiCodexRemoteThreadDetail.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteThreadDetailDecodeResult) = (
            FfiConverterOptionalTypeFfiCodexRemoteThreadDetail.allocationSize(value.`thread`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FfiCodexRemoteThreadDetailDecodeResult, buf: ByteBuffer) {
            FfiConverterOptionalTypeFfiCodexRemoteThreadDetail.write(value.`thread`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}



data class FfiCodexRemoteThreadListDecodeResult (
    var `threads`: List<FfiCodexRemoteThreadSummary>
    ,
    var `errorMessage`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteThreadListDecodeResult: FfiConverterRustBuffer<FfiCodexRemoteThreadListDecodeResult> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteThreadListDecodeResult {
        return FfiCodexRemoteThreadListDecodeResult(
            FfiConverterSequenceTypeFfiCodexRemoteThreadSummary.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteThreadListDecodeResult) = (
            FfiConverterSequenceTypeFfiCodexRemoteThreadSummary.allocationSize(value.`threads`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FfiCodexRemoteThreadListDecodeResult, buf: ByteBuffer) {
            FfiConverterSequenceTypeFfiCodexRemoteThreadSummary.write(value.`threads`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}



data class FfiCodexRemoteThreadSummary (
    var `id`: kotlin.String
    ,
    var `title`: kotlin.String
    ,
    var `updatedAt`: kotlin.String
    ,
    var `cwd`: kotlin.String?
    ,
    var `projectName`: kotlin.String

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteThreadSummary: FfiConverterRustBuffer<FfiCodexRemoteThreadSummary> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteThreadSummary {
        return FfiCodexRemoteThreadSummary(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteThreadSummary) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`updatedAt`) +
            FfiConverterOptionalString.allocationSize(value.`cwd`) +
            FfiConverterString.allocationSize(value.`projectName`)
    )

    override fun write(value: FfiCodexRemoteThreadSummary, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`updatedAt`, buf)
            FfiConverterOptionalString.write(value.`cwd`, buf)
            FfiConverterString.write(value.`projectName`, buf)
    }
}



data class FfiCodexRemoteTranscriptRow (
    var `id`: kotlin.String
    ,
    var `role`: kotlin.String
    ,
    var `text`: kotlin.String
    ,
    var `status`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteTranscriptRow: FfiConverterRustBuffer<FfiCodexRemoteTranscriptRow> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteTranscriptRow {
        return FfiCodexRemoteTranscriptRow(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteTranscriptRow) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`role`) +
            FfiConverterString.allocationSize(value.`text`) +
            FfiConverterOptionalString.allocationSize(value.`status`)
    )

    override fun write(value: FfiCodexRemoteTranscriptRow, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`role`, buf)
            FfiConverterString.write(value.`text`, buf)
            FfiConverterOptionalString.write(value.`status`, buf)
    }
}



data class FfiCodexRemoteTurnSubmit (
    var `threadId`: kotlin.String
    ,
    var `turnId`: kotlin.String
    ,
    var `status`: kotlin.String
    ,
    var `assistantText`: kotlin.String
    ,
    var `eventCount`: kotlin.ULong

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteTurnSubmit: FfiConverterRustBuffer<FfiCodexRemoteTurnSubmit> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteTurnSubmit {
        return FfiCodexRemoteTurnSubmit(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteTurnSubmit) = (
            FfiConverterString.allocationSize(value.`threadId`) +
            FfiConverterString.allocationSize(value.`turnId`) +
            FfiConverterString.allocationSize(value.`status`) +
            FfiConverterString.allocationSize(value.`assistantText`) +
            FfiConverterULong.allocationSize(value.`eventCount`)
    )

    override fun write(value: FfiCodexRemoteTurnSubmit, buf: ByteBuffer) {
            FfiConverterString.write(value.`threadId`, buf)
            FfiConverterString.write(value.`turnId`, buf)
            FfiConverterString.write(value.`status`, buf)
            FfiConverterString.write(value.`assistantText`, buf)
            FfiConverterULong.write(value.`eventCount`, buf)
    }
}



data class FfiCodexRemoteTurnSubmitDecodeResult (
    var `turn`: FfiCodexRemoteTurnSubmit?
    ,
    var `errorMessage`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiCodexRemoteTurnSubmitDecodeResult: FfiConverterRustBuffer<FfiCodexRemoteTurnSubmitDecodeResult> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteTurnSubmitDecodeResult {
        return FfiCodexRemoteTurnSubmitDecodeResult(
            FfiConverterOptionalTypeFfiCodexRemoteTurnSubmit.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiCodexRemoteTurnSubmitDecodeResult) = (
            FfiConverterOptionalTypeFfiCodexRemoteTurnSubmit.allocationSize(value.`turn`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FfiCodexRemoteTurnSubmitDecodeResult, buf: ByteBuffer) {
            FfiConverterOptionalTypeFfiCodexRemoteTurnSubmit.write(value.`turn`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}



data class FfiConfigDiagnostic (
    var `severity`: FfiDiagnosticSeverity
    ,
    var `code`: kotlin.String
    ,
    var `path`: kotlin.String
    ,
    var `message`: kotlin.String

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiConfigDiagnostic: FfiConverterRustBuffer<FfiConfigDiagnostic> {
    override fun read(buf: ByteBuffer): FfiConfigDiagnostic {
        return FfiConfigDiagnostic(
            FfiConverterTypeFfiDiagnosticSeverity.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FfiConfigDiagnostic) = (
            FfiConverterTypeFfiDiagnosticSeverity.allocationSize(value.`severity`) +
            FfiConverterString.allocationSize(value.`code`) +
            FfiConverterString.allocationSize(value.`path`) +
            FfiConverterString.allocationSize(value.`message`)
    )

    override fun write(value: FfiConfigDiagnostic, buf: ByteBuffer) {
            FfiConverterTypeFfiDiagnosticSeverity.write(value.`severity`, buf)
            FfiConverterString.write(value.`code`, buf)
            FfiConverterString.write(value.`path`, buf)
            FfiConverterString.write(value.`message`, buf)
    }
}



data class FfiHostConfig (
    var `id`: kotlin.String
    ,
    var `label`: kotlin.String
    ,
    var `note`: kotlin.String?
    ,
    var `tags`: List<kotlin.String>
    ,
    var `endpoints`: FfiHostEndpoints

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiHostConfig: FfiConverterRustBuffer<FfiHostConfig> {
    override fun read(buf: ByteBuffer): FfiHostConfig {
        return FfiHostConfig(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterTypeFfiHostEndpoints.read(buf),
        )
    }

    override fun allocationSize(value: FfiHostConfig) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`label`) +
            FfiConverterOptionalString.allocationSize(value.`note`) +
            FfiConverterSequenceString.allocationSize(value.`tags`) +
            FfiConverterTypeFfiHostEndpoints.allocationSize(value.`endpoints`)
    )

    override fun write(value: FfiHostConfig, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`label`, buf)
            FfiConverterOptionalString.write(value.`note`, buf)
            FfiConverterSequenceString.write(value.`tags`, buf)
            FfiConverterTypeFfiHostEndpoints.write(value.`endpoints`, buf)
    }
}



data class FfiHostEndpoints (
    var `ssh`: FfiSshEndpoint?
    ,
    var `codexRemoteControl`: FfiCodexRemoteControlEndpoint?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiHostEndpoints: FfiConverterRustBuffer<FfiHostEndpoints> {
    override fun read(buf: ByteBuffer): FfiHostEndpoints {
        return FfiHostEndpoints(
            FfiConverterOptionalTypeFfiSshEndpoint.read(buf),
            FfiConverterOptionalTypeFfiCodexRemoteControlEndpoint.read(buf),
        )
    }

    override fun allocationSize(value: FfiHostEndpoints) = (
            FfiConverterOptionalTypeFfiSshEndpoint.allocationSize(value.`ssh`) +
            FfiConverterOptionalTypeFfiCodexRemoteControlEndpoint.allocationSize(value.`codexRemoteControl`)
    )

    override fun write(value: FfiHostEndpoints, buf: ByteBuffer) {
            FfiConverterOptionalTypeFfiSshEndpoint.write(value.`ssh`, buf)
            FfiConverterOptionalTypeFfiCodexRemoteControlEndpoint.write(value.`codexRemoteControl`, buf)
    }
}



data class FfiPortableConfigDecodeResult (
    var `document`: FfiPortableConfigDocument?
    ,
    var `diagnostics`: List<FfiConfigDiagnostic>
    ,
    var `errorMessage`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiPortableConfigDecodeResult: FfiConverterRustBuffer<FfiPortableConfigDecodeResult> {
    override fun read(buf: ByteBuffer): FfiPortableConfigDecodeResult {
        return FfiPortableConfigDecodeResult(
            FfiConverterOptionalTypeFfiPortableConfigDocument.read(buf),
            FfiConverterSequenceTypeFfiConfigDiagnostic.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiPortableConfigDecodeResult) = (
            FfiConverterOptionalTypeFfiPortableConfigDocument.allocationSize(value.`document`) +
            FfiConverterSequenceTypeFfiConfigDiagnostic.allocationSize(value.`diagnostics`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FfiPortableConfigDecodeResult, buf: ByteBuffer) {
            FfiConverterOptionalTypeFfiPortableConfigDocument.write(value.`document`, buf)
            FfiConverterSequenceTypeFfiConfigDiagnostic.write(value.`diagnostics`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}



data class FfiPortableConfigDocument (
    var `schemaVersion`: kotlin.UInt
    ,
    var `hosts`: List<FfiHostConfig>

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiPortableConfigDocument: FfiConverterRustBuffer<FfiPortableConfigDocument> {
    override fun read(buf: ByteBuffer): FfiPortableConfigDocument {
        return FfiPortableConfigDocument(
            FfiConverterUInt.read(buf),
            FfiConverterSequenceTypeFfiHostConfig.read(buf),
        )
    }

    override fun allocationSize(value: FfiPortableConfigDocument) = (
            FfiConverterUInt.allocationSize(value.`schemaVersion`) +
            FfiConverterSequenceTypeFfiHostConfig.allocationSize(value.`hosts`)
    )

    override fun write(value: FfiPortableConfigDocument, buf: ByteBuffer) {
            FfiConverterUInt.write(value.`schemaVersion`, buf)
            FfiConverterSequenceTypeFfiHostConfig.write(value.`hosts`, buf)
    }
}



data class FfiPortableConfigEncodeResult (
    var `json`: kotlin.String?
    ,
    var `errorMessage`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiPortableConfigEncodeResult: FfiConverterRustBuffer<FfiPortableConfigEncodeResult> {
    override fun read(buf: ByteBuffer): FfiPortableConfigEncodeResult {
        return FfiPortableConfigEncodeResult(
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiPortableConfigEncodeResult) = (
            FfiConverterOptionalString.allocationSize(value.`json`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FfiPortableConfigEncodeResult, buf: ByteBuffer) {
            FfiConverterOptionalString.write(value.`json`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}



data class FfiSshEndpoint (
    var `address`: kotlin.String
    ,
    var `port`: kotlin.UInt
    ,
    var `username`: kotlin.String?
    ,
    var `credentialRef`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiSshEndpoint: FfiConverterRustBuffer<FfiSshEndpoint> {
    override fun read(buf: ByteBuffer): FfiSshEndpoint {
        return FfiSshEndpoint(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiSshEndpoint) = (
            FfiConverterString.allocationSize(value.`address`) +
            FfiConverterUInt.allocationSize(value.`port`) +
            FfiConverterOptionalString.allocationSize(value.`username`) +
            FfiConverterOptionalString.allocationSize(value.`credentialRef`)
    )

    override fun write(value: FfiSshEndpoint, buf: ByteBuffer) {
            FfiConverterString.write(value.`address`, buf)
            FfiConverterUInt.write(value.`port`, buf)
            FfiConverterOptionalString.write(value.`username`, buf)
            FfiConverterOptionalString.write(value.`credentialRef`, buf)
    }
}



data class FfiTurnStreamProjection (
    var `threadId`: kotlin.String?
    ,
    var `turnId`: kotlin.String?
    ,
    var `assistantText`: kotlin.String
    ,
    var `status`: kotlin.String?
    ,
    var `errorMessage`: kotlin.String?
    ,
    var `eventCount`: kotlin.ULong?
    ,
    var `isTerminal`: kotlin.Boolean

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTurnStreamProjection: FfiConverterRustBuffer<FfiTurnStreamProjection> {
    override fun read(buf: ByteBuffer): FfiTurnStreamProjection {
        return FfiTurnStreamProjection(
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalULong.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: FfiTurnStreamProjection) = (
            FfiConverterOptionalString.allocationSize(value.`threadId`) +
            FfiConverterOptionalString.allocationSize(value.`turnId`) +
            FfiConverterString.allocationSize(value.`assistantText`) +
            FfiConverterOptionalString.allocationSize(value.`status`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`) +
            FfiConverterOptionalULong.allocationSize(value.`eventCount`) +
            FfiConverterBoolean.allocationSize(value.`isTerminal`)
    )

    override fun write(value: FfiTurnStreamProjection, buf: ByteBuffer) {
            FfiConverterOptionalString.write(value.`threadId`, buf)
            FfiConverterOptionalString.write(value.`turnId`, buf)
            FfiConverterString.write(value.`assistantText`, buf)
            FfiConverterOptionalString.write(value.`status`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
            FfiConverterOptionalULong.write(value.`eventCount`, buf)
            FfiConverterBoolean.write(value.`isTerminal`, buf)
    }
}



data class FfiTurnStreamProjectionResult (
    var `projection`: FfiTurnStreamProjection?
    ,
    var `errorMessage`: kotlin.String?

){





    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFfiTurnStreamProjectionResult: FfiConverterRustBuffer<FfiTurnStreamProjectionResult> {
    override fun read(buf: ByteBuffer): FfiTurnStreamProjectionResult {
        return FfiTurnStreamProjectionResult(
            FfiConverterOptionalTypeFfiTurnStreamProjection.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FfiTurnStreamProjectionResult) = (
            FfiConverterOptionalTypeFfiTurnStreamProjection.allocationSize(value.`projection`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FfiTurnStreamProjectionResult, buf: ByteBuffer) {
            FfiConverterOptionalTypeFfiTurnStreamProjection.write(value.`projection`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}




enum class FfiDiagnosticSeverity {

    ERROR,
    WARNING;




    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeFfiDiagnosticSeverity: FfiConverterRustBuffer<FfiDiagnosticSeverity> {
    override fun read(buf: ByteBuffer) = try {
        FfiDiagnosticSeverity.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: FfiDiagnosticSeverity) = 4UL

    override fun write(value: FfiDiagnosticSeverity, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalULong: FfiConverterRustBuffer<kotlin.ULong?> {
    override fun read(buf: ByteBuffer): kotlin.ULong? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterULong.read(buf)
    }

    override fun allocationSize(value: kotlin.ULong?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterULong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.ULong?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterULong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiCodexRemoteControlEndpoint: FfiConverterRustBuffer<FfiCodexRemoteControlEndpoint?> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteControlEndpoint? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiCodexRemoteControlEndpoint.read(buf)
    }

    override fun allocationSize(value: FfiCodexRemoteControlEndpoint?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiCodexRemoteControlEndpoint.allocationSize(value)
        }
    }

    override fun write(value: FfiCodexRemoteControlEndpoint?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiCodexRemoteControlEndpoint.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiCodexRemoteHealth: FfiConverterRustBuffer<FfiCodexRemoteHealth?> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteHealth? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiCodexRemoteHealth.read(buf)
    }

    override fun allocationSize(value: FfiCodexRemoteHealth?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiCodexRemoteHealth.allocationSize(value)
        }
    }

    override fun write(value: FfiCodexRemoteHealth?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiCodexRemoteHealth.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiCodexRemoteThreadDetail: FfiConverterRustBuffer<FfiCodexRemoteThreadDetail?> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteThreadDetail? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiCodexRemoteThreadDetail.read(buf)
    }

    override fun allocationSize(value: FfiCodexRemoteThreadDetail?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiCodexRemoteThreadDetail.allocationSize(value)
        }
    }

    override fun write(value: FfiCodexRemoteThreadDetail?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiCodexRemoteThreadDetail.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiCodexRemoteTurnSubmit: FfiConverterRustBuffer<FfiCodexRemoteTurnSubmit?> {
    override fun read(buf: ByteBuffer): FfiCodexRemoteTurnSubmit? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiCodexRemoteTurnSubmit.read(buf)
    }

    override fun allocationSize(value: FfiCodexRemoteTurnSubmit?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiCodexRemoteTurnSubmit.allocationSize(value)
        }
    }

    override fun write(value: FfiCodexRemoteTurnSubmit?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiCodexRemoteTurnSubmit.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiPortableConfigDocument: FfiConverterRustBuffer<FfiPortableConfigDocument?> {
    override fun read(buf: ByteBuffer): FfiPortableConfigDocument? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiPortableConfigDocument.read(buf)
    }

    override fun allocationSize(value: FfiPortableConfigDocument?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiPortableConfigDocument.allocationSize(value)
        }
    }

    override fun write(value: FfiPortableConfigDocument?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiPortableConfigDocument.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiSshEndpoint: FfiConverterRustBuffer<FfiSshEndpoint?> {
    override fun read(buf: ByteBuffer): FfiSshEndpoint? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiSshEndpoint.read(buf)
    }

    override fun allocationSize(value: FfiSshEndpoint?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiSshEndpoint.allocationSize(value)
        }
    }

    override fun write(value: FfiSshEndpoint?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiSshEndpoint.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeFfiTurnStreamProjection: FfiConverterRustBuffer<FfiTurnStreamProjection?> {
    override fun read(buf: ByteBuffer): FfiTurnStreamProjection? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeFfiTurnStreamProjection.read(buf)
    }

    override fun allocationSize(value: FfiTurnStreamProjection?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeFfiTurnStreamProjection.allocationSize(value)
        }
    }

    override fun write(value: FfiTurnStreamProjection?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeFfiTurnStreamProjection.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiCodexRemoteThreadSummary: FfiConverterRustBuffer<List<FfiCodexRemoteThreadSummary>> {
    override fun read(buf: ByteBuffer): List<FfiCodexRemoteThreadSummary> {
        val len = buf.getInt()
        return List<FfiCodexRemoteThreadSummary>(len) {
            FfiConverterTypeFfiCodexRemoteThreadSummary.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiCodexRemoteThreadSummary>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiCodexRemoteThreadSummary.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiCodexRemoteThreadSummary>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiCodexRemoteThreadSummary.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiCodexRemoteTranscriptRow: FfiConverterRustBuffer<List<FfiCodexRemoteTranscriptRow>> {
    override fun read(buf: ByteBuffer): List<FfiCodexRemoteTranscriptRow> {
        val len = buf.getInt()
        return List<FfiCodexRemoteTranscriptRow>(len) {
            FfiConverterTypeFfiCodexRemoteTranscriptRow.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiCodexRemoteTranscriptRow>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiCodexRemoteTranscriptRow.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiCodexRemoteTranscriptRow>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiCodexRemoteTranscriptRow.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiConfigDiagnostic: FfiConverterRustBuffer<List<FfiConfigDiagnostic>> {
    override fun read(buf: ByteBuffer): List<FfiConfigDiagnostic> {
        val len = buf.getInt()
        return List<FfiConfigDiagnostic>(len) {
            FfiConverterTypeFfiConfigDiagnostic.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiConfigDiagnostic>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiConfigDiagnostic.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiConfigDiagnostic>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiConfigDiagnostic.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeFfiHostConfig: FfiConverterRustBuffer<List<FfiHostConfig>> {
    override fun read(buf: ByteBuffer): List<FfiHostConfig> {
        val len = buf.getInt()
        return List<FfiHostConfig>(len) {
            FfiConverterTypeFfiHostConfig.read(buf)
        }
    }

    override fun allocationSize(value: List<FfiHostConfig>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeFfiHostConfig.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FfiHostConfig>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeFfiHostConfig.write(it, buf)
        }
    }
} fun `codexRemoteDecodeHealthJson`(`input`: kotlin.String): FfiCodexRemoteHealthDecodeResult {
            return FfiConverterTypeFfiCodexRemoteHealthDecodeResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_codex_remote_decode_health_json(

        FfiConverterString.lower(`input`),_status)
}
    )
    }

 fun `codexRemoteDecodeThreadDetailJson`(`input`: kotlin.String): FfiCodexRemoteThreadDetailDecodeResult {
            return FfiConverterTypeFfiCodexRemoteThreadDetailDecodeResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_codex_remote_decode_thread_detail_json(

        FfiConverterString.lower(`input`),_status)
}
    )
    }

 fun `codexRemoteDecodeThreadListJson`(`input`: kotlin.String): FfiCodexRemoteThreadListDecodeResult {
            return FfiConverterTypeFfiCodexRemoteThreadListDecodeResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_codex_remote_decode_thread_list_json(

        FfiConverterString.lower(`input`),_status)
}
    )
    }

 fun `codexRemoteDecodeTurnSubmitJson`(`input`: kotlin.String): FfiCodexRemoteTurnSubmitDecodeResult {
            return FfiConverterTypeFfiCodexRemoteTurnSubmitDecodeResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_codex_remote_decode_turn_submit_json(

        FfiConverterString.lower(`input`),_status)
}
    )
    }

 fun `codexRemoteTurnStreamApplyEventJson`(`projection`: FfiTurnStreamProjection, `eventJson`: kotlin.String): FfiTurnStreamProjectionResult {
            return FfiConverterTypeFfiTurnStreamProjectionResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_codex_remote_turn_stream_apply_event_json(

        FfiConverterTypeFfiTurnStreamProjection.lower(`projection`),FfiConverterString.lower(`eventJson`),_status)
}
    )
    }

 fun `codexRemoteTurnStreamEmptyProjection`(): FfiTurnStreamProjection {
            return FfiConverterTypeFfiTurnStreamProjection.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_codex_remote_turn_stream_empty_projection(

        _status)
}
    )
    }

 fun `codexRemoteWireContractVersion`(): kotlin.UInt {
            return FfiConverterUInt.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_codex_remote_wire_contract_version(

        _status)
}
    )
    }

 fun `portableConfigDecodeJson`(`input`: kotlin.String): FfiPortableConfigDecodeResult {
            return FfiConverterTypeFfiPortableConfigDecodeResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_portable_config_decode_json(

        FfiConverterString.lower(`input`),_status)
}
    )
    }

 fun `portableConfigEmptyDocument`(): FfiPortableConfigDocument {
            return FfiConverterTypeFfiPortableConfigDocument.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_portable_config_empty_document(

        _status)
}
    )
    }

 fun `portableConfigEncodeJson`(`document`: FfiPortableConfigDocument): FfiPortableConfigEncodeResult {
            return FfiConverterTypeFfiPortableConfigEncodeResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_portable_config_encode_json(

        FfiConverterTypeFfiPortableConfigDocument.lower(`document`),_status)
}
    )
    }

 fun `portableConfigValidate`(`document`: FfiPortableConfigDocument): List<FfiConfigDiagnostic> {
            return FfiConverterSequenceTypeFfiConfigDiagnostic.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_ct_core_fn_func_portable_config_validate(

        FfiConverterTypeFfiPortableConfigDocument.lower(`document`),_status)
}
    )
    }
